### ISSUE TITLE
3 Error found

### ISSUE THREAD

**Issue by manishbathla** [EZTEQ/slant-cms#11]
Notice: Undefined index: site in C:\xampp\htdocs\slantcms\index.php on line 9
Notice: Undefined variable: blogposts in C:\xampp\htdocs\slantcms\inc\dbfunctions.php on line 53
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\slantcms\templates\home.php on line 4

**Comment by EZTEQ** [comment]
slant-cms isn't usable in it's current state. @MrSmooth and me are actually looking into new technologies to build up slant-cms from scratch.
